/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.avbravo.reportsmart;

import com.avbravo.reportsmart.beans.Atributos;
import com.avbravo.reportsmart.beans.Entidad;
import com.avbravo.reportsmart.domains.EntityReader;
import com.avbravo.reportsmart.domains.MySession;
import com.avbravo.reportsmart.domains.Parameters;
import com.avbravo.reportsmart.domains.Utilidades;
import com.avbravo.reportsmart.jasper.JasperAllGenerador;
import com.avbravo.reportsmart.projects.ProyectoInformacion;
import java.awt.GridBagConstraints;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import org.netbeans.api.project.Project;
import org.netbeans.api.project.ProjectManager;
import org.netbeans.api.project.ui.OpenProjects;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.filesystems.FileObject;
import org.openide.filesystems.FileUtil;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
 
/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//com.avbravo.reportsmart//ReportSmart//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "ReportSmartTopComponent",
        iconBase = "com/avbravo/reportsmart/print.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "explorer", openAtStartup = false)
@ActionID(category = "Window", id = "com.avbravo.reportsmart.ReportSmartTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_ReportSmartAction",
        preferredID = "ReportSmartTopComponent"
)
@Messages({
    "CTL_ReportSmartAction=ReportSmart",
    "CTL_ReportSmartTopComponent=ReportSmart Window",
    "HINT_ReportSmartTopComponent=This is a ReportSmart window"
})
public final class ReportSmartTopComponent extends TopComponent {

    private GridBagConstraints constraints = new GridBagConstraints();
    NotifyDescriptor nd;
    Boolean entityValid = false;
    Boolean parametersValid = false;
    List<Parameters> parametersList = new ArrayList<>();
//    DefaultMutableTreeNode root = new DefaultMutableTreeNode("Report");
//    DefaultMutableTreeNode fieldNode = new DefaultMutableTreeNode("Field");
//    DefaultMutableTreeNode parametersNode = new DefaultMutableTreeNode("Parameters");
    DefaultMutableTreeNode root ;
    DefaultMutableTreeNode fieldNode;
    DefaultMutableTreeNode parametersNode ;
    DefaultTreeModel modelo;

    Boolean moveField = false;
    Boolean moveParameters = false;
    String nameOfFieldOrParameters = "";

    public ReportSmartTopComponent() {
        initComponents();
        jTabbedPane1.remove(jPanelDesign);
        jTabbedPane1.remove(jPanelCode);
        entityValid = false;
        parametersValid = false;
        setName(Bundle.CTL_ReportSmartTopComponent());
        setToolTipText(Bundle.HINT_ReportSmartTopComponent());
        
       root = new DefaultMutableTreeNode("Report");
 fieldNode = new DefaultMutableTreeNode("Field");
   parametersNode = new DefaultMutableTreeNode("Parameters");
        
        
        modelo = new DefaultTreeModel(root);
        jTree1.setModel(modelo);

        modelo.insertNodeInto(fieldNode, root, 0);
        modelo.insertNodeInto(parametersNode, root, 1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelProyecto = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNameOfReport = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNameOfPackage = new javax.swing.JTextField();
        jButtonRefresh = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jTextFieldNameOfProject = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaEntity = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextAreaParameters = new javax.swing.JTextArea();
        jButtonGotoPage2 = new javax.swing.JButton();
        jPanelDesign = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jEditorPaneSummer = new javax.swing.JEditorPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        jEditorPaneTitle = new javax.swing.JEditorPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        jEditorPaneColumnHeader = new javax.swing.JEditorPane();
        jScrollPane14 = new javax.swing.JScrollPane();
        jEditorPanePageHeader = new javax.swing.JEditorPane();
        jScrollPane15 = new javax.swing.JScrollPane();
        jEditorPaneDetails = new javax.swing.JEditorPane();
        jScrollPane16 = new javax.swing.JScrollPane();
        jEditorPaneColumnFooter = new javax.swing.JEditorPane();
        jScrollPane17 = new javax.swing.JScrollPane();
        jEditorPanePageFooter = new javax.swing.JEditorPane();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButtonGotoPage1 = new javax.swing.JButton();
        jButtonGotoPage3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jButtonAddParameter1 = new javax.swing.JButton();
        jLabelSelected = new javax.swing.JLabel();
        jLabelTest = new javax.swing.JLabel();
        jPanelCode = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel4 = new javax.swing.JPanel();
        jButtonGotoPage2From3 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jTextFieldTitle2 = new javax.swing.JTextField();
        jTextFieldTitle0 = new javax.swing.JTextField();
        jCheckBoxDateTitle = new javax.swing.JCheckBox();
        jTextFieldTitle1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jEditorPaneNode = new javax.swing.JEditorPane();

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jPanel5.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jLabel2.text")); // NOI18N

        jTextFieldNameOfReport.setText(org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jTextFieldNameOfReport.text")); // NOI18N
        jTextFieldNameOfReport.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNameOfReportKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNameOfReportKeyPressed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jLabel4.text")); // NOI18N

        jTextFieldNameOfPackage.setText(org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jTextFieldNameOfPackage.text")); // NOI18N
        jTextFieldNameOfPackage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNameOfPackageKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNameOfPackageKeyPressed(evt);
            }
        });

        jButtonRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/avbravo/reportsmart/resources/refresh.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButtonRefresh, org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jButtonRefresh.text")); // NOI18N
        jButtonRefresh.setToolTipText(org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jButtonRefresh.toolTipText")); // NOI18N
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jLabel6.text")); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(jTextFieldNameOfReport, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(4, 4, 4)
                .addComponent(jTextFieldNameOfPackage, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRefresh)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextFieldNameOfReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel4)
                        .addComponent(jTextFieldNameOfPackage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonRefresh))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jPanel6.border.title"))); // NOI18N

        jTextFieldNameOfProject.setEditable(false);
        jTextFieldNameOfProject.setText(org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jTextFieldNameOfProject.text")); // NOI18N

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/avbravo/reportsmart/resources/project.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton2, org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNameOfProject, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNameOfProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jLabel7.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jLabel5.text")); // NOI18N

        jTextAreaEntity.setColumns(20);
        jTextAreaEntity.setRows(5);
        jTextAreaEntity.setToolTipText(org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jTextAreaEntity.toolTipText")); // NOI18N
        jTextAreaEntity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextAreaEntityKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTextAreaEntity);

        jTextAreaParameters.setColumns(20);
        jTextAreaParameters.setRows(5);
        jTextAreaParameters.setToolTipText(org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jTextAreaParameters.toolTipText")); // NOI18N
        jTextAreaParameters.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextAreaParametersKeyPressed(evt);
            }
        });
        jScrollPane10.setViewportView(jTextAreaParameters);

        jButtonGotoPage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/avbravo/reportsmart/resources/next_1.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButtonGotoPage2, org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jButtonGotoPage2.text")); // NOI18N
        jButtonGotoPage2.setToolTipText(org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jButtonGotoPage2.toolTipText")); // NOI18N
        jButtonGotoPage2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGotoPage2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButtonGotoPage2)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(jButtonGotoPage2)
                        .addGap(56, 56, 56))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanelProyectoLayout = new javax.swing.GroupLayout(jPanelProyecto);
        jPanelProyecto.setLayout(jPanelProyectoLayout);
        jPanelProyectoLayout.setHorizontalGroup(
            jPanelProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProyectoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelProyectoLayout.createSequentialGroup()
                .addGroup(jPanelProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 315, Short.MAX_VALUE))
        );
        jPanelProyectoLayout.setVerticalGroup(
            jPanelProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProyectoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(429, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jPanelProyecto.TabConstraints.tabTitle"), jPanelProyecto); // NOI18N

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jPanel9.border.title"))); // NOI18N

        jEditorPaneSummer.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jEditorPaneSummer.border.title"))); // NOI18N
        jScrollPane11.setViewportView(jEditorPaneSummer);

        jEditorPaneTitle.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jEditorPaneTitle.border.title"))); // NOI18N
        jScrollPane12.setViewportView(jEditorPaneTitle);

        jEditorPaneColumnHeader.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jEditorPaneColumnHeader.border.title"))); // NOI18N
        jScrollPane13.setViewportView(jEditorPaneColumnHeader);

        jEditorPanePageHeader.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jEditorPanePageHeader.border.title"))); // NOI18N
        jScrollPane14.setViewportView(jEditorPanePageHeader);

        jEditorPaneDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jEditorPaneDetails.border.title"))); // NOI18N
        jScrollPane15.setViewportView(jEditorPaneDetails);

        jEditorPaneColumnFooter.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jEditorPaneColumnFooter.border.title"))); // NOI18N
        jScrollPane16.setViewportView(jEditorPaneColumnFooter);

        jEditorPanePageFooter.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jEditorPanePageFooter.border.title"))); // NOI18N
        jScrollPane17.setViewportView(jEditorPanePageFooter);

        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/avbravo/reportsmart/resources/compile.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jButton1.text")); // NOI18N
        jButton1.setToolTipText(org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jButton1.toolTipText")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonGotoPage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/avbravo/reportsmart/resources/back.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButtonGotoPage1, org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jButtonGotoPage1.text")); // NOI18N
        jButtonGotoPage1.setToolTipText(org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jButtonGotoPage1.toolTipText")); // NOI18N
        jButtonGotoPage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGotoPage1ActionPerformed(evt);
            }
        });

        jButtonGotoPage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/avbravo/reportsmart/resources/next_1.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButtonGotoPage3, org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jButtonGotoPage3.text")); // NOI18N
        jButtonGotoPage3.setToolTipText(org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jButtonGotoPage3.toolTipText")); // NOI18N
        jButtonGotoPage3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGotoPage3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/avbravo/reportsmart/resources/saverun.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton4, org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jButton4.text")); // NOI18N
        jButton4.setToolTipText(org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jButton4.toolTipText")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Details", "Title", "Page Header", "Column Header", "Column Footer", "Page Footer", "Summary" }));

        jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree1ValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(jTree1);

        jButtonAddParameter1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/avbravo/reportsmart/resources/add.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButtonAddParameter1, org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jButtonAddParameter1.text")); // NOI18N
        jButtonAddParameter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddParameter1ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabelSelected, org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jLabelSelected.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabelTest, org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jLabelTest.text")); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jButtonGotoPage3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelSelected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabelTest, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 15, Short.MAX_VALUE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonGotoPage1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAddParameter1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddParameter1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonGotoPage1)
                .addGap(37, 37, 37)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonGotoPage3)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabelSelected)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTest)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane16, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane17)
                    .addComponent(jScrollPane11)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelDesignLayout = new javax.swing.GroupLayout(jPanelDesign);
        jPanelDesign.setLayout(jPanelDesignLayout);
        jPanelDesignLayout.setHorizontalGroup(
            jPanelDesignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDesignLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelDesignLayout.setVerticalGroup(
            jPanelDesignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDesignLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jPanelDesign.TabConstraints.tabTitle"), jPanelDesign); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jPanel3.border.title"))); // NOI18N

        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonGotoPage2From3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/avbravo/reportsmart/resources/back.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButtonGotoPage2From3, org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jButtonGotoPage2From3.text")); // NOI18N
        jButtonGotoPage2From3.setToolTipText(org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jButtonGotoPage2From3.toolTipText")); // NOI18N
        jButtonGotoPage2From3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGotoPage2From3ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButton3, org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jButton3.text")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButton5, org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jButton5.text")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButton6, org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jButton6.text")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonGotoPage2From3)
                .addGap(27, 27, 27)
                .addComponent(jButton3)
                .addGap(30, 30, 30)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap(163, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5)
                        .addComponent(jButton6))
                    .addComponent(jButtonGotoPage2From3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCodeLayout = new javax.swing.GroupLayout(jPanelCode);
        jPanelCode.setLayout(jPanelCodeLayout);
        jPanelCodeLayout.setHorizontalGroup(
            jPanelCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCodeLayout.createSequentialGroup()
                .addGroup(jPanelCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCodeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCodeLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCodeLayout.setVerticalGroup(
            jPanelCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCodeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(479, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jPanelCode.TabConstraints.tabTitle"), jPanelCode); // NOI18N

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jPanel10.border.title"))); // NOI18N

        jTextFieldTitle2.setText(org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jTextFieldTitle2.text")); // NOI18N

        jTextFieldTitle0.setText(org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jTextFieldTitle0.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jCheckBoxDateTitle, org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jCheckBoxDateTitle.text")); // NOI18N
        jCheckBoxDateTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDateTitleActionPerformed(evt);
            }
        });

        jTextFieldTitle1.setText(org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jTextFieldTitle1.text")); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jScrollPane5.setViewportView(jEditorPaneNode);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTitle0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldTitle1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jTextFieldTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxDateTitle)
                .addGap(402, 402, 402))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jTextFieldTitle0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxDateTitle, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 375, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 263, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(ReportSmartTopComponent.class, "ReportSmartTopComponent.jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// Ponemos el cursor al final del texto
        jTextPane1.setCaretPosition(jTextPane1.getStyledDocument().getLength());

// insertamos un JButton
        JButton boton = new JButton("Pulsame");
        jTextPane1.insertComponent(boton);
        JPanel p = new JPanel();
        jTextPane1.insertComponent(p);
        JComboBox combo;
        combo = new JComboBox();
        combo.addItem("uno");
        combo.addItem("dos");
        combo.addItem("tres");
        jTextPane1.insertComponent(combo);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonGotoPage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGotoPage1ActionPerformed
        jTabbedPane1.remove(jPanelDesign);
        jTabbedPane1.remove(jPanelCode);
        jTabbedPane1.add(jPanelProyecto, "Project");
    }//GEN-LAST:event_jButtonGotoPage1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            String t = jTextPane1.getText();
            System.out.println("--->" + t);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        drawTemplate();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButtonGotoPage3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGotoPage3ActionPerformed
        jTabbedPane1.remove(jPanelDesign);
        jTabbedPane1.remove(jPanelProyecto);
        jTabbedPane1.add(jPanelCode, "Code");
    }//GEN-LAST:event_jButtonGotoPage3ActionPerformed

    private void jButtonGotoPage2From3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGotoPage2From3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.remove(jPanelCode);
        jTabbedPane1.remove(jPanelProyecto);
        jTabbedPane1.add(jPanelDesign, "Design");
    }//GEN-LAST:event_jButtonGotoPage2From3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MySession.setCompilarReporteaJasper("no");
        JasperAllGenerador jasperAllGenerador = new JasperAllGenerador();
        jasperAllGenerador.generar();
        MySession.informacion("Se compilo el reporte");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        saveReportAndCompile();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextAreaParametersKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaParametersKeyPressed
        // TODO add your handling code here:
        processParametersKey();
    }//GEN-LAST:event_jTextAreaParametersKeyPressed

    private void jTextAreaEntityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaEntityKeyPressed
        readkeyClass();
    }//GEN-LAST:event_jTextAreaEntityKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            JFileChooser projectChooser = new JFileChooser();
            projectChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            projectChooser.showOpenDialog(null);

            File projectToBeOpenedFile = projectChooser.getSelectedFile();
            if (projectToBeOpenedFile == null) {
                MySession.advertencia("Seleccione un proyecto web");
                jTextFieldNameOfProject.setText("");
                return;
            }
            FileObject projectToBeOpened = FileUtil.toFileObject(projectToBeOpenedFile);

            Project project = ProjectManager.getDefault().findProject(projectToBeOpened);
            if (project == null) {
                MySession.advertencia("Seleccione un proyecto Web");
                jTextFieldNameOfProject.setText("");
                return;

            }
            Project[] array = new Project[1];
            array[0] = project;
            OpenProjects.getDefault().open(array, false);
            /*
            *
             */
            String lnombre_proyecto = project.getProjectDirectory().getName();

            jTextFieldNameOfProject.setText(lnombre_proyecto);
            //  project.getProjectDirectory();

            ProyectoInformacion projectInformation = new ProyectoInformacion();
            if (projectInformation.getInformation(project)) {
                if (!MySession.isEsProyectoWeb()) {
                    nd = new NotifyDescriptor.Message("Seleccione un proyecto Web");
                    DialogDisplayer.getDefault().notify(nd);
                    jTextFieldNameOfProject.setText("");
                    return;
                }
                // jTextFieldReportShortPath.setText(MySession.getReportShortPath());
            }

        } catch (Exception ex) {
            MySession.error("Error" + ex.toString());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        generateNameReport();
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jTextFieldNameOfPackageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNameOfPackageKeyPressed
        generateNameReport();
    }//GEN-LAST:event_jTextFieldNameOfPackageKeyPressed

    private void jTextFieldNameOfPackageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNameOfPackageKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameOfPackageKeyTyped

    private void jTextFieldNameOfReportKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNameOfReportKeyPressed
        generateNameReport();
    }//GEN-LAST:event_jTextFieldNameOfReportKeyPressed

    private void jTextFieldNameOfReportKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNameOfReportKeyTyped

    }//GEN-LAST:event_jTextFieldNameOfReportKeyTyped

    private void jButtonGotoPage2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGotoPage2ActionPerformed
        try {
             root = new DefaultMutableTreeNode("Report");
 fieldNode = new DefaultMutableTreeNode("Field");
   parametersNode = new DefaultMutableTreeNode("Parameters");
        
        
        modelo = new DefaultTreeModel(root);
        jTree1.setModel(modelo);

        modelo.insertNodeInto(fieldNode, root, 0);
        modelo.insertNodeInto(parametersNode, root, 1);
            Integer countnode = 0;
            entityValid = true;
            parametersValid = true;
            jEditorPaneColumnFooter.setText("");
            jEditorPaneColumnHeader.setText("");
            jEditorPaneDetails.setText("");
            jEditorPanePageFooter.setText("");
            jEditorPanePageHeader.setText("");
            jEditorPaneSummer.setText("");
            jEditorPaneTitle.setText("");

            MySession.getEntidadList().removeAll(MySession.getEntidadList());

            if (jTextFieldNameOfProject.getText().equals("")) {
                MySession.error("Seleccione el proyecto web");
                return;
            }
            if (jTextFieldNameOfReport.getText().isEmpty() || jTextFieldNameOfReport.getText().equals("")) {
                MySession.error("Indique el nombre del reporte");
                return;
            }
            if (jTextFieldNameOfPackage.getText().equals("")) {
                MySession.error("Indique el nombre del paquete");
                return;
            }
            if (jTextAreaEntity.getText().equals("")) {
                MySession.error("Ingrese la clase a procesar");
                jTextAreaEntity.requestFocus();
                return;
            }
            //
            MySession.setAllTablesWithPrimaryKey(false);
            EntityReader entityReader = new EntityReader();
            entityReader.readEntity(jTextFieldNameOfReport.getText(), jTextAreaEntity.getText());
            if (MySession.getEntidadList().isEmpty()) {
                entityValid = false;
            }
            if (!entityValid) {
                MySession.advertencia("La clase no es valida");
                return;
            }
            if (!parametersValid) {
                MySession.advertencia("Los Parametros no son validos");
                return;
            }
            if (!MySession.getAllTablesWithPrimaryKey()) {
                MySession.advertencia("No hay ningun atributo con llave primaria @Id");
                return;
            }
            String endline = "";
         

            for (Entidad e : MySession.getEntidadList()) {
                Integer count = 0;
                for (Atributos a : e.getAtributosList()) {
                    count++;
                    if (count < 5) {
                        endline = "";
                    } else {
                        count = 0;
                        endline = "\n";
                    }
                    String separator = "";
                    if (!jEditorPaneColumnHeader.getText().equals("")) {
                        separator = ",";
                    }

                 

                    jEditorPaneColumnHeader.setText(jEditorPaneColumnHeader.getText() + separator + a.getNombre() + endline);
                    jEditorPaneDetails.setText(jEditorPaneDetails.getText() + separator + " F_" + a.getNombre() + endline);
                    DefaultMutableTreeNode fielddata = new DefaultMutableTreeNode(a.getNombre());
                    modelo.insertNodeInto(fielddata, fieldNode, countnode++);

                }

            }

            jEditorPaneTitle.setText(jTextFieldNameOfReport.getText());
            jEditorPanePageHeader.setText("Fecha: _Date()");
            jEditorPanePageFooter.setText("Pagina: _numberPage()");

            //-- parametros
            readParameters();
            if (!parametersList.isEmpty()) {
                for (Parameters p : parametersList) {
                    jEditorPaneTitle.setText(jEditorPaneTitle.getText() + " " + p.getName());
                }

            }

            MySession.setNameOfProject(jTextFieldNameOfProject.getText());
            MySession.setNameOfReport(jTextFieldNameOfReport.getText());
            //            MySession.setReportShortPath(jTextFieldReportShortPath.getText());
            MySession.setNameOfPackage(jTextFieldNameOfPackage.getText());
            jTabbedPane1.add(jPanelDesign, "Desing");
            jTabbedPane1.remove(jPanelProyecto);
            jTabbedPane1.remove(jPanelCode);

        } catch (Exception e) {
            MySession.error("Error" + e.toString());
        }
    }//GEN-LAST:event_jButtonGotoPage2ActionPerformed

    private void jCheckBoxDateTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDateTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxDateTitleActionPerformed

    private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree1ValueChanged
        try {

            DefaultMutableTreeNode nodoSeleccionado;
            nodoSeleccionado = (DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent();
//eventosNodoSeleccionado(nodoSeleccionado);

            String s = " ";
            jEditorPaneNode.setText("\n");
            jEditorPaneNode.setText("hola");
            /**
             * Obtenemos la ruta seleccionada
             */
            TreePath rutaSeleccionada = evt.getPath();
            Object[] nodos = rutaSeleccionada.getPath();
            for (int i = 0; i < nodos.length; i++) {
                Object nodo = nodos[i];
                s += nodo.toString() + " / ";
            }
            s += "\n";
            if (s.contains("")) {
                jLabelSelected.setText(s);
            }

            if (s.contains("Report / Field /")) {
                String t = s.replace("Report / Field /", "");
                if (t.contains("/")) {
                    t = t.replace("/", "");
                }
                nameOfFieldOrParameters = t;
                jLabelTest.setText(t);

            } else {
                if (s.contains("Report / Parameters /")) {
                    String t = s.replace("Report / Parameters /", "");
                    if (t.contains("/")) {
                        t = t.replace("/", "");
                    }
                    nameOfFieldOrParameters = t;
                    jLabelTest.setText(t);
                }
            }
//            jEditorPaneNode.setText(s);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTree1ValueChanged

    private void jButtonAddParameter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddParameter1ActionPerformed
        try {
            String separator = "";
            nameOfFieldOrParameters = nameOfFieldOrParameters.trim();
            String search ="";
           
            switch (jComboBox1.getSelectedItem().toString().trim()) {
                case "Title":
                    search="[" +nameOfFieldOrParameters+"]";
                    if (jEditorPaneTitle.getText().isEmpty() || jEditorPaneTitle.getText().equals("")) {
                        separator = ",";
                    }

                    if (jEditorPaneTitle.getText().contains(search)) {
                        MySession.advertencia("Ese parametro ya esta en la banda TITLE");
                        return;
                    }
                    jEditorPaneTitle.setText(jEditorPaneTitle.getText() + "  " + search);
                    break;
                case "Details":
search="[F_" +nameOfFieldOrParameters+"]";
                    if (jEditorPaneDetails.getText().isEmpty() || jEditorPaneDetails.getText().equals("")) {
                        separator = ",";
                    }
                    if (jEditorPaneDetails.getText().contains(search)) {
                        MySession.advertencia("Ese campo ya esta en la banda Fields");
                        return;
                    }
                    jEditorPaneDetails.setText(jEditorPaneDetails.getText() + separator + search);
                    break;
                case "Page Header":
                    break;

                case "Column Header":
                    break;
                case "Column Footer":
                    break;
                case "Page Footer":
                    break;
                case "Summary":
                    break;
            }

        } catch (Exception e) {
            MySession.error("error() " + e.getLocalizedMessage());
        }
    }//GEN-LAST:event_jButtonAddParameter1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonAddParameter1;
    private javax.swing.JButton jButtonGotoPage1;
    private javax.swing.JButton jButtonGotoPage2;
    private javax.swing.JButton jButtonGotoPage2From3;
    private javax.swing.JButton jButtonGotoPage3;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JCheckBox jCheckBoxDateTitle;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JEditorPane jEditorPaneColumnFooter;
    private javax.swing.JEditorPane jEditorPaneColumnHeader;
    private javax.swing.JEditorPane jEditorPaneDetails;
    private javax.swing.JEditorPane jEditorPaneNode;
    private javax.swing.JEditorPane jEditorPanePageFooter;
    private javax.swing.JEditorPane jEditorPanePageHeader;
    private javax.swing.JEditorPane jEditorPaneSummer;
    private javax.swing.JEditorPane jEditorPaneTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelSelected;
    private javax.swing.JLabel jLabelTest;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelCode;
    private javax.swing.JPanel jPanelDesign;
    private javax.swing.JPanel jPanelProyecto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextAreaEntity;
    private javax.swing.JTextArea jTextAreaParameters;
    private javax.swing.JTextField jTextFieldNameOfPackage;
    private javax.swing.JTextField jTextFieldNameOfProject;
    private javax.swing.JTextField jTextFieldNameOfReport;
    private javax.swing.JTextField jTextFieldTitle0;
    private javax.swing.JTextField jTextFieldTitle1;
    private javax.swing.JTextField jTextFieldTitle2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    private void generateNameReport() {
        try {
//            jTextFieldReportShortPath.setText(MySession.getReportShortPath() + jTextFieldNameOfPackage.getText() + MySession.getFileSeparator() + jTextFieldNameOfReport.getText() + ".jrxml");
            MySession.setReportShortPath(MySession.getReportShortPath() + jTextFieldNameOfPackage.getText() + MySession.getFileSeparator() + jTextFieldNameOfReport.getText() + ".jrxml");
            MySession.setNameOfReport(jTextFieldNameOfReport.getText());
            MySession.setNameOfPackage(jTextFieldNameOfPackage.getText());
        } catch (Exception e) {
            MySession.error("Error" + e.getLocalizedMessage());
        }
    }

    private void drawEditor() {
        try {
            // Atributos para la frase, en negrita
            SimpleAttributeSet attrs = new SimpleAttributeSet();
            StyleConstants.setBold(attrs, true);
// Se inserta
            jTextPane1.getStyledDocument().insertString(jTextPane1.getStyledDocument().getLength(), jEditorPaneSummer.getText(), attrs);
        } catch (Exception e) {
            MySession.error("Error" + e.getLocalizedMessage());
        }
    }

    private void drawTemplate() {
        try {
            String template = " <?xml version=\"1.0\" encoding=\"UTF-8\"?> \n\n"
                    + "<jasperReport>\n\n"
                    + "<background>\n\n"
                    + "     <band splitType=\"Stretch\"/>\n\n"
                    + "</background>\n\n"
                    + "<title>\n\n"
                    + "<band height=\"79\" splitType=\"Stretch\"/>\n\n"
                    + "</title>\n\n"
                    + "<pageHeader>\n\n"
                    + "<band height=\"35\" splitType=\"Stretch\"/>\n\n"
                    + "</pageHeader>\n\n"
                    + "<columnHeader>\n\n"
                    + "<band height=\"61\" splitType=\"Stretch\"/>\n\n"
                    + "</columnHeader>\n\n"
                    + "<detail>\n\n"
                    + "<band height=\"125\" splitType=\"Stretch\"/>\n\n"
                    + "</detail>\n\n"
                    + "<columnFooter>\n\n"
                    + "<band height=\"45\" splitType=\"Stretch\"/>\n\n"
                    + "</columnFooter>\n\n"
                    + "<pageFooter>\n\n"
                    + "<band height=\"54\" splitType=\"Stretch\"/>\n\n"
                    + "</pageFooter>\n\n"
                    + "<summary>\n\n"
                    + "<band height=\"42\" splitType=\"Stretch\"/>\n\n"
                    + "</summary>\n\n"
                    + "</ jasperReport >\n\n";
            jTextPane1.removeAll();
            SimpleAttributeSet attrs = new SimpleAttributeSet();
            StyleConstants.setBold(attrs, true);
// Se inserta
            jTextPane1.getStyledDocument().insertString(
                    jTextPane1.getStyledDocument().getLength(), template, attrs);

        } catch (Exception e) {
            MySession.error("drawTemplate()" + e.getLocalizedMessage());
        }

    }

    private void readkeyClass() {
        try {

            int lines = jTextAreaEntity.getLineCount();
            for (int i = 0; i < lines; i++) {
                int start = jTextAreaEntity.getLineStartOffset(i);
                int end = jTextAreaEntity.getLineEndOffset(i);
                // Implement method processLine
                String line = jTextAreaEntity.getText(start, end - start);
                System.out.println("texto " + line);
                if (line.equals("pub")) {
                    jTextAreaEntity.setText(jTextAreaEntity.getText() + "lic class ");
                } else {
                    if (line.contains("public class")) {
                        String x = line.replace("public class", "");
                        x = x.replace("{", "").toLowerCase().trim();
                        if (!jTextAreaEntity.getText().contains("{")) {
                            jTextFieldNameOfPackage.setText(x);
                        }
                        if (!jTextAreaEntity.getText().contains("{")) {
                            jTextFieldNameOfReport.setText(x);
                        }
                        if (!jTextAreaEntity.getText().contains("@Id") && jTextAreaEntity.getText().contains("{")) {
                            jTextAreaEntity.setText(jTextAreaEntity.getText() + "\n@Id");
                        }
                    } else {
                        line = line.trim();
                        System.out.println("line: " + line);
                        if (line.equals("pub")) {
                            jTextAreaEntity.setText(jTextAreaEntity.getText() + "lic class ");
                        }
                        if (line.equals("pr")) {
                            jTextAreaEntity.setText(jTextAreaEntity.getText() + "ivate ");
                        }
                        if (line.equals("private St") || line.equals("private st")) {
                            jTextAreaEntity.setText(jTextAreaEntity.getText() + "ring ");
                        }

                        if (line.equals("private In") || line.equals("private in")) {
                            jTextAreaEntity.setText(jTextAreaEntity.getText() + "teger ");
                        }
                        if (line.equals("private Do") || line.equals("private do")) {
                            jTextAreaEntity.setText(jTextAreaEntity.getText() + "uble ");
                        }
                        if (line.equals("private Da") || line.equals("private da")) {
                            jTextAreaEntity.setText(jTextAreaEntity.getText() + "te ");
                        }
                    }
                }

            }

//            for (String line : jTextAreaEntity.getText().split("\\n")) {
            generateNameReport();
        } catch (Exception e) {
            MySession.error("readkeyClass()" + e.getLocalizedMessage());
        }

    }

    private void processParametersKey() {
        try {

            int lines = jTextAreaParameters.getLineCount();
            for (int i = 0; i < lines; i++) {
                int start = jTextAreaParameters.getLineStartOffset(i);
                int end = jTextAreaParameters.getLineEndOffset(i);
                // Implement method processLine
                String line = jTextAreaParameters.getText(start, end - start);

                line = line.trim();
                if (line.equals("St") || line.equals("st")) {
                    jTextAreaParameters.setText(jTextAreaParameters.getText() + "ring P_");
                }

                if (line.equals("In") || line.equals("in")) {
                    jTextAreaParameters.setText(jTextAreaParameters.getText() + "teger P_");
                }
                if (line.equals("Do") || line.equals("do")) {
                    jTextAreaParameters.setText(jTextAreaParameters.getText() + "uble P_");
                }
                if (line.equals("Da") || line.equals("da")) {
                    jTextAreaParameters.setText(jTextAreaParameters.getText() + "te P_");
                }
            }
            //  jTextAreaParameters.setText(jTextAreaParameters.getText().toUpperCase());

        } catch (Exception e) {
            MySession.error("processParametersKey()" + e.getLocalizedMessage());
        }

    }

    /**
     * lee los parametros
     */
    private void readParameters() {
        try {
            Integer countnode = 0;
            parametersValid = false;
           
            parametersList = new ArrayList<>();
            if (jTextAreaParameters.getText().isEmpty()) {
                parametersValid = true;
                return;
            }
            for (String line : jTextAreaParameters.getText().split("\\n")) {
                String s = line;
                if (s.contains("private")) {
                    s = s.replace("private", "");
                }

                s = s.replace(";", "");
                s = s.trim();
                String[] splited = s.split("\\s");
//                atributos.setTipo(splited[0]);
                String name = splited[1];
                String type = Utilidades.mysqlToJava(splited[0]);
                Parameters parameters = new Parameters(name, type);
                parametersList.add(parameters);
              
                DefaultMutableTreeNode fieldparameters = new DefaultMutableTreeNode(name);
                modelo.insertNodeInto(fieldparameters, parametersNode, countnode++);
            }
            MySession.setParametersList(parametersList);
            parametersValid = true;
        } catch (Exception e) {
            MySession.error("readkeyClass()" + e.getLocalizedMessage());
            parametersValid = false;
        }

    }

    private void saveReportAndCompile() {
        try {
            MySession.setTitleBand(jEditorPaneTitle.getText());
            MySession.setPageHeaderBand(jEditorPanePageHeader.getText());
            MySession.setColumnHeaderBand(jEditorPaneColumnHeader.getText());
            MySession.setDetailBand(jEditorPaneDetails.getText());
            MySession.setColummFooterBand(jEditorPaneColumnFooter.getText());
            MySession.setPageFooterBand(jEditorPanePageFooter.getText());
            MySession.setSummaryBand(jEditorPaneSummer.getText());
            MySession.setCompilarReporteaJasper("si");
            JasperAllGenerador jasperAllGenerador = new JasperAllGenerador();
            jasperAllGenerador.generar();
            MySession.informacion("Se genero y se compilo el reporte");
        } catch (Exception e) {
            MySession.error("saveReportAndCompile()" + e.getLocalizedMessage());
        }
    }

    private Boolean isValidParameters(String texto) {
        try {
            for (String line : texto.split("\\n")) {
                String s = line;
                if (s.contains("P_")) {

                    //SS
                    s = s.replace("private", "");
                }
                line = line.trim();
            }

            return true;
        } catch (Exception e) {
            MySession.error("isValidParameters()" + e.getLocalizedMessage());
        }
        return false;
    }
}
